.TH OUI "1" "August 2024" "Jacob Niemeir" "User Commands"
.SH NAME
oui \- find the manufacturer of a given NIC 
.SH SYNOPSIS
.B oui <MAC Address>

.SH COPYRIGHT
Copyright \(co 2024 Jacob Niemeir.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
